# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  adapter: sqlite3
  encoding: unicode
  database: quotes_development
  pool: 5
  username: eek

test: &test
  adapter: sqlite3
  encoding: unicode
  database: quotes_test
  pool: 5
  username: eek
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: quotes_production
  host: localhost
  pool: 5
  username: eek
  password: password
