# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d5020c2bc2e9cc0068d78baf68d179049048139f07b66a409612ed531de48c8b64dbad5581815f89a32abe062e6f6dafbcd97dd01261c7c5f418f31b4c7a54e

test:
  secret_key_base: 3cb16434edec37e46d0a9eb07de2ff6278529722ab312282a47b6e7a8aa63e4fb5aeee5a95d2f92c9bbdde4dc01ab9a1e8673272bc9566a0eaf13a15044ebb64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
